### ISSUE TITLE
баг с крафтами

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#101]
### Тип используемого модпака

Default

### Среда запуска

на серваке

### Новые миры

Да

### Ожидаемое поведение

надо что бы было так( из большой было 3 из средней 2 а из малой 1)
![image](https://user-images.githubusercontent.com/112543401/220457738-f2fc6002-0e6a-4320-bd46-1ca526ef09f8.png)

### Фактическое поведение

получается так ( у всех 1)
![image](https://user-images.githubusercontent.com/112543401/220458016-fb4b4cb9-e698-4cf2-a7da-4a8fa5ab8c1f.png)

### Действия по воспроизведению

скачивай сборку открывай майн и чекай крафты

### Дополнительная информация

ты слишком оффициальный

**Comment by Xikaro** [comment]
Не баг, кожа разная
