### ISSUE TITLE
Stone tools quests unobtainable 

### ISSUE THREAD

**Issue by Cupesh** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#103]
### Version modpack Used

Extended

### Environment

Open to LAN

### New Worlds

Yes

### Expected Behavior

Crafting stone tools like knife, shovel, axe should result in completed quest

### Actual Behavior

The quests are not registered 

### Steps to Reproduce

The quest is not registered 

### Additional Information

V 2.4.1

**Comment by Cupesh** [comment]
@Xikaro Hi. This has not been fixed for the extended version

**Comment by Xikaro** [comment]
This has not yet been released if nothing is there at night, I will release 4.2.2

**Comment by Cupesh** [comment]
Ok, thank you
