### ISSUE TITLE
Gregtech knife cannot scrape soaked hide

### ISSUE THREAD

**Issue by Cupesh** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#104]
### Version modpack Used

Extended

### Environment

Open to LAN

### New Worlds

Unsure

### Expected Behavior

Gregtech stone knife should be able to be used to scrape hide

### Actual Behavior

Gregtech:knife item loses Ore dictionary "knife" name if not at full durability resulting in not being able to scrape hide

### Steps to Reproduce

place soaked hide on a log, craft a new stone knife -> can be used once to scrape a small piece, then does not work
if the knife is repaired or a new one is crafted then it can scrape again once

**Comment by BabBimmaBome** [comment]
also having the same issue stone knife and copper both dont work for scraping soaked hide didnt test any others.
Works in creative only

**Comment by msgerbs** [comment]
This seems to be the same issue as was fixed here 3 years ago: https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/48f34e989c40792a36719762d2538c9be29f2da5

**Comment by SpeeeDCraft** [comment]
Lol, it's gtceu bug, fixed on own side, wait for next update
