### ISSUE TITLE
баг ,связанный с ножем и необработанной шкурой

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#106]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

должно почистить кожу 

### Фактическое поведение

после первого воспользования нож больше не обраьбатывает кожу ![image](https://user-images.githubusercontent.com/112543401/221883040-a9ec0eb9-e769-4018-809a-6ef6dc51cfca.png)

### Действия по воспроизведению

попытатся обработать кожу

### Дополнительная информация

ординфпри потере прочности у ножа исчезает ордината

нож с потерей
![image](https://user-images.githubusercontent.com/112543401/221883377-ec9486bd-2d9c-4832-a702-4dec3c563267.png)
 
нож починенный
![image](https://user-images.githubusercontent.com/112543401/221883571-b6cc6d05-527a-49c1-91bb-68907af4ae47.png)

**Comment by Xikaro** [comment]
Баг гт, ждем исправления
https://github.com/GregTechCEu/GregTech/issues/1452

**Comment by Xikaro** [comment]
#104 
дубль
