### ISSUE TITLE
одинаковые крафты для разных форм экструдера

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#107]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

крафты должны быть разными

### Фактическое поведение

крафт формочки эксрудера(наконечник молотка)
![image](https://user-images.githubusercontent.com/112543401/221884279-37f40ed9-5c91-4f6e-bc07-4c46261af34a.png)
крафт формочки эксрудера(наконечник кирки)
![image](https://user-images.githubusercontent.com/112543401/221884850-0d8945e6-2f97-40af-938c-566b1b1aaf80.png)

### Действия по воспроизведению

чекнуть jei

### Дополнительная информация

перемести кусачкив крафте формы кирки куда нибудь(все крафты с формой экструдера (слиток)
![image](https://user-images.githubusercontent.com/112543401/221884760-d984e182-59c2-4268-abad-fa453cf20d63.png)

**Comment by Xikaro** [comment]
исправлено в дев
