### ISSUE TITLE
No higher power level chainsaws and wrenches.

### ISSUE THREAD

**Issue by BurgerFan45** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#109]
### Version modpack Used

Default

### Environment

Server Multiplayer & Singleplayer

### New Worlds

Yes

### Expected Behavior

In 4.1.12 you could make chainsaws and wrenches with all power units (LV-IV)

### Actual Behavior

Currently in 4.2.2 only LV wrenches and chainsaws are possible to craft, also they look funny when held.

### Steps to Reproduce

Check recipes for power tools, also try drilling with a drill and see how it looks.

**Comment by Xikaro** [comment]
fixed in dev
