### ISSUE TITLE
Inventory Bogo Sorter present on server but not client in 4.2.2-extended

### ISSUE THREAD

**Issue by msgerbs** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#110]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Mods on server would match the client and I could join the server.

### Actual Behavior

Inventory Bogo Sorter is present on the server but not on the client, so I can't join the server due to a server mod rejection:

![image](https://user-images.githubusercontent.com/1313921/222244850-626bbe88-b1fc-4255-832a-6b98490a61cd.png)

### Steps to Reproduce

Download the server pack and run it. Install the modpack on curseforge. Try to join the server, get mod rejection.

### Additional Information

It looks like this mod was supposed to be removed in 4.2.2 but was left in the server pack and just needs to be removed.

**Comment by Xikaro** [comment]
fixed in dev
