### ISSUE TITLE
Infinite water cover requires IV materials instead of HV materials

### ISSUE THREAD

**Issue by Sehrank8** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#113]
### Version modpack Used

Extended

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Infinite water cover made with HV materials
![Ekran görüntüsü 2023-03-02 215708](https://user-images.githubusercontent.com/64368795/222528981-93fe8334-f830-4fd8-9407-2d6c0fd115d5.png)
![Ekran görüntüsü 2023-03-02 215744](https://user-images.githubusercontent.com/64368795/222528987-d9772d74-a566-491d-888c-31e239360991.png)
![Ekran görüntüsü 2023-03-02 215800](https://user-images.githubusercontent.com/64368795/222528995-55f23bb7-1f64-4aef-b269-c3fb02f9f14a.png)

### Actual Behavior

Infinite water cover requires IV materials

### Steps to Reproduce

Lookup infinite water cover in JEI

**Comment by Sehrank8** [comment]
Also how do I get a large amount of vanilla water? Fresh water in gregtech machines don't work

**Comment by kirilsgekiss** [comment]
@Sehrank8 You can build OpenComputer robot, that will right click fresh water using water bottle and then empty it into TFC barrel. It was possible on previous versions, but now OC does not have recipes for some reason.
Also you can freeze fresh water in multiblock freezer and then melt it into vanilla water. (At least JEI says so)

**Comment by Xikaro** [comment]
His recipe was once changed, and I forgot to move it in era IV
In the future, it is planned to make fresh water by default in GT machines, or make a generation of vanilla water instead of fresh

**Comment by Sehrank8** [comment]
@Xikaro when will you make that chabge?
