### ISSUE TITLE
Ошибка при крафте телескопа

### ISSUE THREAD

**Issue by Boottov** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#114]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

При крафте телескопа получаем телескоп

### Фактическое поведение

Создаются поножи неподготовленного космического скафандра 1-го уровня

### Действия по воспроизведению

1)Зайти на сервер
2)Развиться до EV эры
3)Создать Улучшенную сборочную машину III
4)Поместить в неё (IV сенсор)x3 (Алюминий(Плотная пластина))х8 (Стеклянная линза)х3 (Суперкомпьютер)х2 (EV Сенсор)х2 (Интегральная схема конфигурация:7)х1

### Дополнительная информация

Конфликт конфигурация интегральных схем

**Comment by Xikaro** [comment]
Хоть бы скрин приложили, с чем конфликтует(

**Comment by Xikaro** [comment]
исправлено в дев
