### ISSUE TITLE
все крафты ае2 в верстаке походу не работают

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#115]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

должнор скрафтится
![image](https://user-images.githubusercontent.com/112543401/222920666-16231f01-8667-4f6d-bfdf-875d6f7ae56b.png)

### Фактическое поведение

не крафтится
![image](https://user-images.githubusercontent.com/112543401/222920673-0af402b2-ab48-4e7f-b6da-780e109d3fe3.png)
 не инвентарь не верстак нигде

### Действия по воспроизведению

скрафти

### Дополнительная информация

мб ты уже знаешь об этом

**Comment by Xikaro** [comment]
исправлено
