### ISSUE TITLE
Не редактируется центральный монитор

### ISSUE THREAD

**Issue by CTPaHHInK** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#118]
### Version modpack Used

Default

### Environment

Мультиплеер, свой сервер

### New Worlds

No

### Expected Behavior

При нажатии на пустой/заполненный слот структуры Центральный монитор будет доступно редактирование этого слота

### Actual Behavior

Не открывается режим редактирования слота

### Steps to Reproduce

Построить Центральный монитор, открыть его интерфейс, пытаться отредактировать слот для информации

### Additional Information

Возможно это на стороне сервера

**Comment by CTPaHHInK** [comment]
[https://youtu.be/Yza5XvVhwiU](url)

**Comment by Xikaro** [comment]
исправлено в дев
