### ISSUE TITLE
Квест на квантовый мост

### ISSUE THREAD

**Issue by TheGalaxx** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#12]
Квантовая сингулярность не засчитывается
![image](https://user-images.githubusercontent.com/105606748/193315202-805c51e0-56c2-408d-aa8e-1e5b6cc06abd.png)
![image](https://user-images.githubusercontent.com/105606748/193315246-c76b8752-51c2-4770-96d5-21aac39806b3.png)

**Comment by Xikaro** [comment]
Исправлено в dev
