### ISSUE TITLE
багс пластинной

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#120]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

предмет должен юзатся в крафте но когда кладу в крафт  он не обрабатывается
![image](https://user-images.githubusercontent.com/112543401/223178091-6c086e53-2446-4b03-947d-65dd1a27ffc0.png)

### Фактическое поведение

![image](https://user-images.githubusercontent.com/112543401/223177571-3f3ef8b0-00a0-40be-a327-5a2455baab8c.png)

### Действия по воспроизведению

возможно  такая пластина только у меня но я думаю что это изза конвликтов теры и грега

**Comment by Xikaro** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/55663835/223834181-0b470802-c4cc-4ba8-98f1-a8891b164a50.png)
Исправлено в дев
