### ISSUE TITLE
Used tools missing Oredictionary value

### ISSUE THREAD

**Issue by TFCAPW** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#121]
### Version modpack Used

Default

### Environment

Singleplayer

### New Worlds

Unsure

### Expected Behavior

Hammers of any durability can be put in anvils. 

### Actual Behavior

For example, hammers used for welding ingots together lose 1 durability.  This durability loss removes the oredictionary tag "hammer" from the tool, so it can no longer be put in the Anvil for other uses.  This also happens with a knife, for instance when removing the wool from sheepskin loses the "knife" tag, meaning the knife can no longer be used for cutting open rubber trees to make latex.

<img width="320" alt="OreDictionary" src="https://user-images.githubusercontent.com/126911227/223823046-c12faedc-47b5-482d-96c5-28801fc3b54a.png">

### Steps to Reproduce

Craft a stone hammer. 
Use the hammer in some way to reduce its durability
Try to put the hammer in an anvil, it will no accept it.

**Comment by Xikaro** [comment]
#106 #104 fix in dev
