### ISSUE TITLE
Не крафтится двигатель ракеты Т1

### ISSUE THREAD

**Issue by Boottov** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#125]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Нет

### Ожидаемое поведение

Крафт Двигателя ракеты Т1
![2023-03-10_07 10 04](https://user-images.githubusercontent.com/124869774/224245594-0a34ffd3-9e33-405f-ab1a-a023a6cb1bcc.png)

### Фактическое поведение

Не крафтится Двигатель ракеты Т1

### Действия по воспроизведению

Мультиблочный сборщик с LuV контроллером напряжения, 4A IV энергетическим входом, жидкостным входом, предметным входом, и предметным выходом. В предметный вход положить 
![2023-03-10_07 19 08](https://user-images.githubusercontent.com/124869774/224244591-fd6e22f0-8c1b-4939-a949-458e80cfc8b7.png)
В жидкостный входной люк залить 288мб припоя

### Дополнительная информация

Возможно ошибка в том что сборщик в чистой комнате, или капсуле из галактика

**Comment by Xikaro** [comment]
![Screenshot_25](https://user-images.githubusercontent.com/55663835/224732999-26dd499f-703e-48c6-8112-9cae5776c365.png)

**Comment by Xikaro** [comment]
![Screenshot_26](https://user-images.githubusercontent.com/55663835/224734088-1d2f31b6-54e6-40e6-82cf-17f9890e3f29.png)
![Screenshot_27](https://user-images.githubusercontent.com/55663835/224734099-9c5f12d1-cf50-4f0c-b37e-8048548d80c0.png)
крафтится
