### ISSUE TITLE
Неправильные слитки после парового молота

### ISSUE THREAD

**Issue by Scarecrowest** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#126]
### Тип используемого модпака

Default

### Среда запуска

мультиплеер

### Новые миры

Нет

### Ожидаемое поведение

![image](https://user-images.githubusercontent.com/73081044/224301634-fb7eaaf2-9626-44c0-a783-36993f9e10bf.png)
Из высокоуглеродного слитка должен получится обычный слиткой красной стали

### Фактическое поведение

Получается багованный слиток не участвующий в крафтах, его можно только переплавить. Такая же история с голубой, черной и обычной сталью
![image](https://user-images.githubusercontent.com/73081044/224301870-83ee2e36-e603-4e0c-82de-adfdb47f2103.png)
![image](https://user-images.githubusercontent.com/73081044/224301902-7465d823-2fb1-4c7c-bfb7-d6878f783453.png)

### Действия по воспроизведению

Высокоуглеродные слитки сунуть в паровой котел

### Дополнительная информация

При обычной ковке получаются нормальные слитки. При автоматической вот такое говно

**Comment by Xikaro** [comment]
втф

**Comment by SpeeeDCraft** [comment]
:trollface: :

**Comment by Xikaro** [comment]
исправлено в дев
