### ISSUE TITLE
Salt Bucket cannot be crafted into Salt

### ISSUE THREAD

**Issue by TheRedHulk** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#129]
### Version modpack Used

Extended

### Environment

Singleplayer and Forge Server

### New Worlds

Yes

### Expected Behavior

Wooden Bucket with Salt should be able to be crafted into small piles of dust. The recipe shows up in JEI.

### Actual Behavior

No craft result is possible. I tried it in both the player inventory craft window and a craft bench. This happens for all players on server and in singleplayer.

### Steps to Reproduce

Attempt to craft bucket of salt (from drying salt water), into salt piles.

**Comment by Xikaro** [comment]
![Screenshot_24](https://user-images.githubusercontent.com/55663835/224731526-c0a8c68b-5215-461f-a4ae-e234151e9882.png)
fixed in dev

**Comment by TheRedHulk** [comment]
Clean install on a new instance in Prism Launcher is where those screenshots were taken from.
