### ISSUE TITLE
расширенная версия, баг верстака и кристала из астрала

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#148]
### Тип используемого модпака

Default

### Среда запуска

одиночка

### Новые миры

Да

### Ожидаемое поведение

должно скрафтиться на верстаке из деревьев тфк 
![image](https://user-images.githubusercontent.com/112543401/229134718-b228019a-0300-41cc-b98d-c7f8c8eb0e84.png)
 луч не летит к верстку
 луч работает даже днём 

### Фактическое поведение

 на верстаке из ванили крафтится
![image](https://user-images.githubusercontent.com/112543401/229135314-b742bded-4a4e-41ff-bb95-81b436043d8a.png)
![image](https://user-images.githubusercontent.com/112543401/229135365-d9438824-159c-40c5-9d64-ffcd4315a58c.png) 

на верстаке из мода не крафтится
![image](https://user-images.githubusercontent.com/112543401/229136416-a9157b23-6388-48cf-8ab0-1d3bf333da49.png)
![image](https://user-images.githubusercontent.com/112543401/229136470-7fc89545-64c5-4d9e-ba67-3d2de7dd0cd4.png)

### Действия по воспроизведению

воспользуйся этим сидом и кордами чтобы найти место с кристалом быстро 
 сид -237758559
корды
/tp 178 147 -123

### Дополнительная информация

Xikaro — Сегодня, в 15:22
бл, а я хз как это фиксить
миксином наверное, но хз

**Comment by tocandyman** [comment]
```
луч не летит к верстку
луч работает даже днём
```

Луч вроде должен лететь вертикально вниз, если его не привязывать специальной палкой отдельно.
Кристалл(луч) работает всегда и не зависит от времени суток.

**Comment by FriendlyCube** [comment]
> ```
> луч не летит к верстку
> луч работает даже днём
> ```
> 
> Луч вроде должен лететь вертикально вниз, если его не привязывать специальной палкой отдельно. Кристалл(луч) работает всегда и не зависит от времени суток.

блин, ща понял что написал не понятно, в общем, луч летит к ванильному верстаку при любом из условий, при этом к мод воркбенчу ни при каких из условий он не летиьт, а крафт на нём не делается
