### ISSUE TITLE
Programmed Circuit Duplication

### ISSUE THREAD

**Issue by Bunny12343** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#15]
**Describe the bug**
This bug abuses a weird crafting mechanic for the Programmed Circuit, crafted from the shapeless LV-tier electronic circuit recipe.

**To Reproduce**
1. Place the LV-tier circuit into the player crafting grid
2. Hold ctrl and press left click on the crafting result
3. The Programmed Circuit pops into the inventory without consuming the LV-tier electronic circuit.

**Expected behavior**
The LV-tier circuit should be consumed in the crafting.

**Modpack**
 - Modpack TFGR4.1.4-Huge -

**Comment by Xikaro** [comment]
Fixed in the next version of GTCEu

**Comment by Xikaro** [comment]
the error was not on the side of GT, and much more extensive, but it was fixed
