### ISSUE TITLE
TFC Metals Duplication Bug

### ISSUE THREAD

**Issue by Bunny12343** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#16]
**Describe the bug**
The bug allows for duplicating TFC metals by using 1 heated metal ingot to create a pickaxe head in the TFC anvil, then melting it in the gregtech arc furnace to get 3 ingots back.

**To Reproduce**
1. Heat up a TFC metal ingot in the crucible (e.g blue steel ingot)
2. Create a pickaxe head in the TFC anvil (e.g tier 6 anvil -> blue steel pickaxe head)
3. Place the pickaxe head into the arc furnace to get 3 ingots back, giving 2 free ingots.

**Expected behavior**
The arc furnace should return 1 ingot for the pickaxe recipe. Also, the recipes regarding tools made out of TFC metals in gregtech machines should be disabled.

**Modpack**
 - Modpack TFG R4.1.4-Huge

**Comment by Xikaro** [comment]
![Screenshot_245](https://user-images.githubusercontent.com/55663835/194217031-8d98c220-fe3f-4a58-a40f-72b9d548d960.png)
![Screenshot_244](https://user-images.githubusercontent.com/55663835/194217041-63252a48-0063-440b-8b44-5a4a5856c855.png)
![Screenshot_243](https://user-images.githubusercontent.com/55663835/194217045-24d2e642-e6a9-42de-89ee-01278773f55e.png)

**Comment by SpeeeDCraft** [comment]
fixed in dev, thanks
