### ISSUE TITLE
Кривой рендер сундуков из флоры

### ISSUE THREAD

**Issue by BayerHeroine** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#17]
### Modpack Used

TFG 4.1.4

### Environment

Везде

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

В обычном ТФК (а так же у некоторых сундуков из флоры (African Padauk например)) место стыка крышки и самого сундука рендерится норм.
![image](https://user-images.githubusercontent.com/105360606/194050848-105d87e8-b39b-45fd-8c9f-9c3a688f1fa8.png)

### Actual Behavior

Но у большинства других сундуков из флоры в месте стыка начинается рябь. 
![image](https://user-images.githubusercontent.com/105360606/194050749-dc926c98-9738-4186-8297-cda9accb8686.png)

### Steps to Reproduce

1) Поставить сундук, добавляемый флорой (Например из дерева Greenheart)
2) Наслаждаться рябью

### Additional Information

Исходя из того, что у всех сундуков из ТФК и флоры используется одна и та же модель сундука, я могу лишь предположить, что проблема в коде из флоры, который вероятно недоделан (судя по тому, что некоторые сундуки отображаются норм).

**Comment by Xikaro** [comment]
Знаю как пофиксить, предположу, что это просто не кривая текстура, имеющая разные цвета/оттенки в местах стыка, решением будет изменить текстуру в местах стыков крышки и самого сундука

**Comment by BayerHeroine** [comment]
Ты прав, я сравнил текстуры и отличия действительно есть у кривых сундуков.

**Comment by BayerHeroine** [comment]
[assets.zip](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/9716069/assets.zip)
Я исправил текстуры.

**Comment by Xikaro** [comment]
Отлично, спасибо большое, войдет в следующий релиз
