### ISSUE TITLE
Теряется древесина при рубке топором из грегтеха

### ISSUE THREAD

**Issue by BayerHeroine** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#18]
### Modpack Used

TFG 4.1.4

### Environment

Везде

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

Когда топором рубишь дерево, то теряется 1 древесина. Если это одиночный блок дерева (или если рубишь с шифтом), то он не выпадет совсем. 

### Actual Behavior

При этом с пилой или ТФКшным топором (каменным) такого бага нет.

### Steps to Reproduce

1) Взять топор из гречки
2) Срубить одиночный блок дерева
3) Ничего не получить

**Comment by Xikaro** [comment]
С новой системой рубки, если нажать шифт, и рубить, дерево выпадает
