### ISSUE TITLE
Сделать возможность делать тропинки для блоков из флоры

### ISSUE THREAD

**Issue by BayerHeroine** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#20]
### Modpack Used

TFG 4.1.4

### Related Problem

Лопаты не делают дорожки из различных вариаций земли из флоры (каменистая, песчанная и т.п.), из-за чего их прокладка превращается в гемор по перекопке земли (чтоб они превратились в обычную грязь, которую можно превратить в дорожку).

### Your Solution

Сделать разные вариации земли пригодные к трансформации в тропинки.

**Comment by nemo48rus** [comment]
А можно скрин такой земли? Я чёт ни разу не видел вариаций..

**Comment by BayerHeroine** [comment]
![image](https://user-images.githubusercontent.com/105360606/194759585-8692fdf2-6610-4b35-a56a-57edb36b6974.png)
Вот как пример. Или подзол.

**Comment by nemo48rus** [comment]
Получается либо на сервере о ключены подобные виды, либо заменены))

Я не встречал никакую из видов - чисто слои земли и камней))

**Comment by Xikaro** [comment]
На серве есть, просто ты не встречал, так как особо по миру не бродил

**Comment by Xikaro** [comment]
Сделаем вместе с форком флоры

**Comment by Xikaro** [comment]
Реализовано в форке
