### ISSUE TITLE
Кувшин с пресной водой отображается пустым

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#22]
### Modpack Used

TFG

### Related Problem

d

### Your Solution

f

### Additional Information

g

**Comment by Xikaro** [comment]
умный?

**Comment by Maximnety** [comment]
а как вставить
![image](https://user-images.githubusercontent.com/84129980/195161433-ba3a08b2-2bf1-4ada-8b7b-0a1027d9c1e9.png)

**Comment by Xikaro** [comment]
во

**Comment by Xikaro** [comment]
только это не предложение, а баг

**Comment by Xikaro** [comment]
Исправлено
