### ISSUE TITLE
Камни

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#26]
### Modpack Used

TFG:NH 4.1.3

### Additional mods

TFC

### Environment

Server

### New Worlds

Unsure

### Cross-Mod Interaction

Yes

### Expected Behavior

![image](https://user-images.githubusercontent.com/84129980/195654177-ee273dcd-00f2-4528-a83a-2f39b3bca5aa.png)

### Actual Behavior

Не у всех камней изменена текстура

### Steps to Reproduce

Зайдите в джей и посмотрите

**Comment by Maximnety** [comment]
![image](https://user-images.githubusercontent.com/84129980/195654080-f9c7bf52-91a8-4b57-a38d-da187e68c094.png)

**Comment by Xikaro** [comment]
плак-плак

**Comment by Xikaro** [comment]
готово
