### ISSUE TITLE
Металлы

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#27]
### Modpack Used

TFG:NH 4.1.3

### Additional mods

TFC

### Environment

Server

### New Worlds

Unsure

### Cross-Mod Interaction

No

### Expected Behavior

![image](https://user-images.githubusercontent.com/84129980/195654447-984808a9-945b-4ef8-8c66-ec6946be9a9b.png)

### Actual Behavior

Если расплавлять в тигле металлы выдаст 70 единиц, когда как инструментам надо 144

### Steps to Reproduce

Зайдите в джей и посмотрите

**Comment by Xikaro** [comment]
это правильное поведение, так и задумано, у разных руд, а точнее их образцов, содержится разное количество металла

**Comment by Xikaro** [comment]
Для получения 144 плавь больше руды, она суммируется
