### ISSUE TITLE
Treated Wood Planks Recipe using a Creosote Cell doesn't consume the Creosote 

### ISSUE THREAD

**Issue by AtelierAmber** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#29]
### Modpack Used

TFG:NH Extended R4.1.4

### Additional mods

Optifine

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

The Creosote should be consumed entirely and the cell should be replaced by an empty cell

### Actual Behavior

https://i.gyazo.com/ef90e6916622156aaf96a19a1fea49f1.mp4

See link for a small gif of what happens. 

### Steps to Reproduce

Try to craft creosote wood planks with a creosote filled empty cell.

### Additional Information

As an appendum; you can't convert from empty cells to universal cells anymore. Not sure if that's intentional or not.

**Comment by Xikaro** [comment]
Fixed in dev
