### ISSUE TITLE
Quest for AE2 singularity registers an engineering processor as a valid completion item

### ISSUE THREAD

**Issue by Bunny12343** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#30]
### Modpack Used

4.1.6a

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Singularity quest should only detect an actual singularity as a valid quest completion item.

### Actual Behavior

Quest for AE2 singularity registers an engineering processor as a valid completion item

### Steps to Reproduce

place an engineering processor into the inventory. quest detects singularity as acquired.

**Comment by Xikaro** [comment]
Fixed in dev
