### ISSUE TITLE
комбинация f3+c крашит

### ISSUE THREAD

**Issue by Neon4301** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#35]
### Modpack Used

R4.16.a

### Environment

сервер

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

иногда случайно в приближении нажимаю ф3

### Actual Behavior

скопировать корды,с оптифайном приближашь и нажимаешь f3 

### Steps to Reproduce

держал с и нажал ф3

**Comment by Xikaro** [comment]
не удалось воспроизвести, скинь пожалуйста крашлог
