### ISSUE TITLE
Мука в мильтиблок паровом дробителе не производится.

### ISSUE THREAD

**Issue by DragonOfSteel** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#36]
### Modpack Used

R4.16.a

### Environment

сервер

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

в рецептах имеется возможность произвести муку из крупы на мультиблок дробителе

### Actual Behavior

мука не производится на мильтиблок дробителе

### Steps to Reproduce

рецепт не работает

**Comment by Xikaro** [comment]
исправлено

**Comment by SpeeeDCraft** [comment]
/* Хз, все протестили, а оно итак работает, если у вас все еще не работает, не стесняйтесь открыть заново этот тикет */
