### ISSUE TITLE
Непереведённый квест

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#37]
### Modpack Used

TFG:NH 4.1.4

### Additional mods

FTB : quests

### Environment

Server

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

Переведённый текст

### Actual Behavior

Текст не переведён
![Uploading image.png…]()

### Steps to Reproduce

Лв эра квест на словарь руд

**Comment by Xikaro** [comment]
Картинки нет(

**Comment by Maximnety** [comment]
Она пытается загрузится но не может

**Comment by Maximnety** [comment]
![image](https://user-images.githubusercontent.com/84129980/201483068-ed004842-d3dc-4785-9ba7-e27e559e7d04.png)
