### ISSUE TITLE
Квест в неправильной эре

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#38]
### Modpack Used

TFG:NH 4.1.4

### Additional mods

FTB : quests

### Environment

Server

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

Квест должен быть в LuV эре
![image](https://user-images.githubusercontent.com/84129980/201514200-2b23a937-6220-4e26-b4a6-23d1ff361e6e.png)

### Actual Behavior

Квест в HV эре
![image](https://user-images.githubusercontent.com/84129980/201514130-7f102ad3-54f0-4ba1-bf90-9d540a43fb8e.png)

### Steps to Reproduce

Откройте HV эру

> все равно не понял, солнечные панели ULV должны быть в UV эре?

**Comment by Xikaro** [comment]
в UV эре?

**Comment by Maximnety** [comment]
> в UV эре?

![image](https://user-images.githubusercontent.com/84129980/201514052-437a2233-6a7e-44fe-9ea9-3f35fc33c2f9.png)
скрины багаются

**Comment by Xikaro** [comment]
все равно не понял, солнечные панели ULV должны быть в UV эре?

**Comment by Maximnety** [comment]
> все равно не понял, солнечные панели ULV должны быть в UV эре?

скрины нормально прикрепить не мог, обновил пост

**Comment by Xikaro** [comment]
теперь понятно
