### ISSUE TITLE
Новые шаблоны для предметов и руд по ор-дикту. "Фильтр для обработки через мехи"

### ISSUE THREAD

**Issue by nemo48rus** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#39]
В мэ должно показываться все доступные для производства пластины, для руд: очищенные руды.

Интерфейс я подумал, что должен быть типа верстака ячеек с окошками для "сканирования" словаря предмета (оредикта).
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/186

**Comment by Xikaro** [comment]
Нам нет смысла это писать, так как влияние на это мы не окажем
