### ISSUE TITLE
Can't craft GregTech tools

### ISSUE THREAD

**Issue by EmperialDev** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#40]
### Version modpack Used

Default

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Making a bronze pickaxe from a bronze pickaxe head.

### Actual Behavior

You can't craft any pickaxes.

### Steps to Reproduce

Take a GregTech tool head, and then try to craft the tool, most doesn't work.

### Additional Information

This effects most GregTech tools, including pickaxes, swords, axes, hammers and more, so you can't craft any of them.

**Comment by EmperialDev** [comment]
This only effects version R4.1.7. In version R4.1.6a you can craft all the tools as expected.

**Comment by Xikaro** [comment]
fixed in dev
