### ISSUE TITLE
Crash of the game when a planted a pumpkin seed

### ISSUE THREAD

**Issue by NoeLoisil** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#41]
### Version modpack Used

Default

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

I planted a second pumpkin seed and the game suddenly crashed

### Crash Report

https://mclo.gs/Q3M0Nln

**Comment by Xikaro** [comment]
What version of modpack do you have?

**Comment by NoeLoisil** [comment]
that was with the version 4.1.6a

**Comment by Xikaro** [comment]
check the latest version, 4.1.8

**Comment by NoeLoisil** [comment]
I updated
