### ISSUE TITLE
Powder Keg Bug

### ISSUE THREAD

**Issue by Patryk1213** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#45]
### Version modpack Used

Default

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When using powder keg it should drop ore chunks.

### Actual Behavior

When using more then 2 stacks of gunpowder in powder keg you get missing textures instead of ore chunks.

### Steps to Reproduce

![before](https://user-images.githubusercontent.com/119159194/204128274-66ab848a-21dc-491b-805a-14b39c35cb7b.png)
![after](https://user-images.githubusercontent.com/119159194/204128276-a0d9791d-ce8a-487c-8ab0-34bc277ecc5a.png)

### Additional Information

Missing textures have same id as ore chunks but you cant do anything with them.

**Comment by Xikaro** [comment]
Lol

**Comment by SpeeeDCraft** [comment]
Thanks

**Comment by SpeeeDCraft** [comment]
I think it's fixed in r4.2.0, if not reopen this
