### ISSUE TITLE
Нет самцов лошадей

### ISSUE THREAD

**Issue by JedaiGames** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#46]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Лошади есть

### Фактическое поведение

Отсутствуют кони-самцы. Везде только кобылы.

### Действия по воспроизведению

Создать мир

Найти лошадь

Это женщина

**Comment by Xikaro** [comment]
возможно ты просто плохо искал, в первом же мире, спустя пару минут поиска, нашел, вес спавна разного пола животных, примерно одинаков
