### ISSUE TITLE
Проблема добычи саженцев

### ISSUE THREAD

**Issue by JedaiGames** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#47]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

При рубке дерева выпадают саженцы

### Фактическое поведение

Саженцы падают только при рубке дерева самым первым каменным топором, из ранней стадии игры.
Как только переходишь на медь дроп саженцев прекращается.

### Действия по воспроизведению

1. Создать мир.
2. Создать каменный топор - срубить дерево
    - саженцы выпадут
3. Развится до меди и срубить дерево медным топором
    - Саженцы не выпадают, независимо от количества листвы, типа дерева и времени года.

**Comment by JedaiGames** [comment]
Дополнительно: возможно это связано с #18? просто предположение, но поскольку медные инструменты теперь считаются греговскими это может быть таковым.

**Comment by Xikaro** [comment]
Впервые слышу про то, что саженцы не падают при рубке, есть шанс выпадения, и на сколько помню, нужно использовать секатор, нож или что то ещё, проверяли совсем недавно

**Comment by Xikaro** [comment]
Так же, щас мы в процессе переписывания тфк под гт, и все несовместимости, будут устранены

**Comment by JedaiGames** [comment]
Понял спасибо.
Просто на ранних стадиях игры рубил деревья топором (не разрушая листву отдельно) и с него обязательно падало несколько саженцев, я так целую кипарисовую рощу рассадил у дома. А сейчас резко перестали. Может от времени года зависит, или я просто невезучий. Непонятно. 
В любом случае спасибо за помощь, и извиняюсь за передоз отзывов в один день.

**Comment by nemo48rus** [comment]
Ничего страшного)) 
Олег привык)
Бывает у него выскакивает парочка активных игроков, они помогают ему баги отловить в паке.
Так и живем

**Comment by Xikaro** [comment]
Проверьте повторно после 4.2.3, если воспроизводится, откройте снова
