### ISSUE TITLE
Фантомные блоки

### ISSUE THREAD

**Issue by JedaiGames** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#51]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Я выкопаю блок.

### Фактическое поведение

Если сломать блок, и в это время сломается инструмент, то на месте блока останется фантомная копия.
Сам блок при этом не выпадает, а пройти сквозь это место невозможно - игрока будет багованым образом выпихивать из этого места.
Единственный способ исправить это - поставить что то на место выкопанного блока.
Тогда блок появится снова, а у тебя в инвентаре окажется фантомный предмет который ты туда поставил - ведь он визуально потратится, но на самом деле останется в инвентаре и продолжит занимать слот
![2022-11-29_15 50 35](https://user-images.githubusercontent.com/63721354/205437490-4808796b-41e2-42ef-8c82-74d6001d05ec.png)
На скриншоте - фантомный блок травы, после того как был скопан лопатой с критическим запасом прочности (лопата сломалась сразу после выкапывания).

### Действия по воспроизведению

1) зайти в мир, скрафтить любой инструмент.
2) начать добывать блоки пока у инструмента не останется минимум прочности.
3) следующий скопаный блок превратится в фантомный как только инструмент сломается.

### Дополнительная информация

Был точно встречен на лопатах и медной кирке, но полагаю распространяется на в принципе любые инструменты и блоки.

**Comment by GIBRID64r** [comment]
Хм, у меня тоже такое было, но только когда быстро копаешь, то тогда фантомные блоки поевлялись

**Comment by JedaiGames** [comment]
Я думаю это баг самого майнкрафта а не сборки. Хотя если это так то это очень печально. Ведь тогда это почти невозможно исправить. И придётся просто с этим жить.

**Comment by GIBRID64r** [comment]
Я играл на одном сервере с гречкой и был бур,когда быстро копаешь фантомные блоки были,Может быть и баг майна

**Comment by nemo48rus** [comment]
> Я думаю это баг самого майнкрафта а не сборки. Хотя если это так то это очень печально. Ведь тогда это почти невозможно исправить. И придётся просто с этим жить.

Баг как я понял лопаты ГТ, так что шанс на фикс этого бага есть, т.е. полировки мода.
Можно попытаться написать в сам ГТ, с ссылкой сюда и ждать исправления.
Если бы был тфк виновником, то можно было бы сразу закрывать вопрос))

Посмотрим что скажет Олег)

**Comment by Xikaro** [comment]
Инструменты гт в глубокой переработке, тфк и всю остальную лабуду мы переписываем почти с нуля, пока оставлю открытым, это вполне возможно возникло из-за отставания майна, но да, это скорее всего проблема самого майна, так что тут не попишешь, если так
