### ISSUE TITLE
Один крафт пыли изменчивого кварца

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#53]
### Тип используемого модпака

Default

### Среда запуска

Server

### Новые миры

Да

### Ожидаемое поведение

Ожидается крафт из всех форм кварца (хотя бы обычной)

### Фактическое поведение

![2022-12-10_07 34 48](https://user-images.githubusercontent.com/84129980/206838484-0b7f0251-b311-41ad-9bca-042141def3b6.png)

### Действия по воспроизведению

Посмотрите в JEI

**Comment by Maximnety** [comment]
Для того чтобы получить пыль из изменчивого кварца надо:
1.)Сделать жидкость в экстракторе
2.)Остудить жидкость в отвердителе и превратить в пластины
3.)Пластину передробить в пыль

**Comment by nemo48rus** [comment]
Ха-ха, да рецепты для мэ постоянно переписываются)
К сожалению до референса в голове ещё жить и жить))
Потребление энергии мизерное, в сравнении)
Сколько у вас один накопитель жрет? 35 Еу/т?

**Comment by Xikaro** [comment]
исправлено в 4.2.0

**Comment by nemo48rus** [comment]
Надо исправить, чтобы кварцевое нечто охлаждались через морозилку и это уже можно было дробить))

**Comment by Xikaro** [comment]
Добавлен стандартный крафт дробления в пыль
