### ISSUE TITLE
Идея: Pam's HarvestCraft

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#55]
### Тип используемого модпака

Default

### Ваше решение

Здравствуйте! Предлагаю добавить в проект PHC. Изначально меня заинтересовал TFC addon: Cooking with TFC, но он только для версии 1.7.10. PHC сможет добавить некоторое доп. разнообразие еды, а также культур и деревьев. Для совместимости с TFC есть addon. Уже пробовал запустить на последней версии модпака и основные функции работали.

### Дополнительная информация

Ссылки:
addon - https://www.curseforge.com/minecraft/mc-mods/tfc-pams-harvestcraft-compatibility-mod,
mod - https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft/.

**Comment by KarandashKosmos** [comment]
*ошибся, правильно pam's harvestcraft.

**Comment by GIBRID64r** [comment]
Было бы прикольно,я знаю этот мод и он очень много еды и семян дает, как разнообразие будет клево

**Comment by KarandashKosmos** [comment]
К стати addon перерабатывает семена PHC в семенаTFC.

**Comment by Xikaro** [comment]
Мод был, его удалили из-за багов и не доработок, возможно будет интегрирован в тфк, когда будем переписывать тфк

**Comment by KarandashKosmos** [comment]
Спасибо, Олег.
