### ISSUE TITLE
Сбой скина

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#56]
### Тип используемого модпака

Default

### Среда запуска

Сервер Forge

### Новые миры

Да

### Ожидаемое поведение

Ничего

### Фактическое поведение

Ошибка скина.
![image](https://user-images.githubusercontent.com/95368060/206867339-b41a760d-e40b-49a4-af1d-78d810fcdcf4.png)

### Действия по воспроизведению

1) Зайти на сервер
2) Прописать /stop
3) Запустить сервер и снова зайти.

**Comment by Xikaro** [comment]
ASM bug, the developer said it will be fixed in the next version
