### ISSUE TITLE
Остатки крафта

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#57]
### Тип используемого модпака

Default

### Среда запуска

Сервер Forge

### Новые миры

Да

### Ожидаемое поведение

Ничего

### Фактическое поведение

Крафтил (в инвентаре), закрыл его. Открываю снова а там (фантомные) остатки.
![image](https://user-images.githubusercontent.com/95368060/207346647-34092d36-c4b3-450a-9be4-429a4e9c9c06.png)

### Действия по воспроизведению

1) Крафтить в инвентаре
2) Закрыть его оставив что-то в сетке крафта
3) Открыть снова

**Comment by Xikaro** [comment]
Оно дюпается или просто остается там?

**Comment by Xikaro** [comment]
Не смог воспроизвести

**Comment by KarandashKosmos** [comment]
Нет они фантомные.

**Comment by Xikaro** [comment]
Повторить можешь?

**Comment by KarandashKosmos** [comment]
Почему-то работает не всегда.

**Comment by KarandashKosmos** [comment]
Я буду играть в течении недели и попробую записать через OBS.
Не закрывайте ещё несколько дней, пожалуйста.

**Comment by KarandashKosmos** [comment]
Просто уже несколько недель иногда замечаю.

**Comment by Xikaro** [comment]
че с гравитацией? Установлены какие то доп моды?

**Comment by KarandashKosmos** [comment]
Нет
