### ISSUE TITLE
Explosives drop ores and gems with no metadata

### ISSUE THREAD

**Issue by PotatoSamurai2** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#59]
### Version modpack Used

Default

### Environment

Single player

### New Worlds

Unsure

### Expected Behavior

Use of a powderkeg to break ore blocks should drop chunks of the corresponding ores.

### Actual Behavior

The drops are textureless placeholders with no metadata.
![](https://i.imgur.com/cU2elqH.png)
![](https://i.imgur.com/HiNdWjD.png)
![](https://i.imgur.com/1LQAuh0.png)
![](https://i.imgur.com/rsIZaTW.png)

### Steps to Reproduce

Use powderkeg with at least 48 Gunpowder on ore blocks.

### Additional Information

Have TFC Elementia installed, and its drops work correctly.

**Comment by SpeeeDCraft** [comment]
Thanks

**Comment by SpeeeDCraft** [comment]
I think it's fixed in r4.2.0, if not, reopen this
