### ISSUE TITLE
Замена бесполезных перекрафтов мелких ячеек

### ISSUE THREAD

**Issue by nemo48rus** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#6]
**Описание того, что вы хотите, чтобы мы сделали**
Уменьшить напряжение на сборных (4к из 1к компонентов) МЭ компоненах чтобы компенсировать их дороговизну по ресурсам в плоть до 16кк ячейки.
Так же можно заменить логический процессор на вычислительный, чтобы были разные схемы крафта и повысилась его дороговизна. 
Игроку нужно будет искать жилу алмазов, если он захочет внепланово обновить свою мэ.
Единственное Я бы сократил количество процессоров до 2, т.к. часть вычислительной силы по логике, уже есть в 1к ячейках и так далее.
Крафтить без автокрафта даже EV схемы проблематично))

(Я до последнего тянул как с графитом, так и с алмазами).

**Опишите альтернативные пути, которые вы бы рассмотрели**
Четкое и краткое описание любых альтернативных решений или функций, которые вы рассмотрели.

**Дополнительно**
![Screenshot_2.png](https://user-images.githubusercontent.com/106464618/190393843-9fe179d2-b55c-497d-9b23-c8734174da51.png)
![Screenshot_3.png](https://user-images.githubusercontent.com/106464618/190393869-3b93006b-f5a1-4e34-8fd5-0888a7cd340b.png)
![Screenshot_4.png](https://user-images.githubusercontent.com/106464618/190393883-e480eca5-b82e-4b3d-95b3-907c87f2aedb.png)

**Comment by Xikaro** [comment]
Хорошее предложение, сделаю

**Comment by Xikaro** [comment]
![Screenshot_158](https://user-images.githubusercontent.com/55663835/190858775-425ffeea-b8b0-4b05-8187-66b832e29e7c.png)
Я не уменьшу напряжение, а сделаю время на выполнение рецепта из компонентов пред идущего тира, в 2 раза меньше, а обычный крафт, выше, т.е местами поменяю, так как есть возможность разбора пред идущих ячеек, и из них делать следующего тира, и каждый тир ячеек сделан с шагом в тир напряжения, в плоть до UV

**Comment by Xikaro** [comment]
![Screenshot_159](https://user-images.githubusercontent.com/55663835/190858922-57653b37-dfd5-4e45-acc8-61fa716b175f.png)

**Comment by nemo48rus** [comment]
Да, сделаешь. Но рецепт в таком случае как был говном, так и остался.

А ты не умеешь мыслить наперед - ты потом поднимешь одиночный крафт на новые напряжения

**Comment by Xikaro** [comment]
С чего ты взял, что я буду понимать? Нет, не планируется

**Comment by Xikaro** [comment]
Рецепт компонентов из 4 шт пред идущих, дешевле по энергии, с тем учётом, что ячейки можно разобрать, т.е в ресурсах ты не просидаешь, ибо они у тебя остаются

**Comment by nemo48rus** [comment]
В каком смысле разобрать? Дизассемблер ввели пока меня не было?
-Нет.
У меня ресурсы подвешены, я стараюсь минимум 64к делать ячейки.

Может быть компромисс?
Включая 16к можно собрать так, как я сказал с понижением тира напряжения - в начале это поможет с крафтом МЭ сети и вообще ячеек выше, чем 1к на шв. 
А остальные крафты делай как хочешь, потому что после 64к я тупо раздавал ячейки, потому что крафт ни о чем.

Разбирать ячейки, потом забивать специально крафт/вручную набирать ресы - дюже геморно, 

НИКТО: Собирает одноступенчатый крафт.
Абсолютно никто: крафтит максимально доступного тира.

Мотив: https://minty.club/artist/taim-aut/noch-luna
Я: Ночь. Луна. Разбираю 4к.
Пу-рум-пурурум-пум-пум
В паааальцах компоненты предательски дрожат!

Образ твой Хикаро!
Вспоминаю уже 4 дня!
Получается полная фигня...

© Таймаут - Ночь луна

Продолжение просить нада; можешь добавить как отсылку/локальный мем
