### ISSUE TITLE
4.1.9 Server pack

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#62]
### Version modpack Used

Default

### Related Problem

Where can I find 4.1.9 server pack? Or maybe there is a chance I can get it working by just replacing 4.1.8 mods folder with 4.1.9 ones?

### Your Solution

-

### Additional Information

-

**Comment by Xikaro** [comment]
I'll post it tonight
