### ISSUE TITLE
Вылет мира при использовании JEI.

### ISSUE THREAD

**Issue by Omirian** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#63]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### С какой стороны краш

Сервер

### Новые миры

Да

### Действия по воспроизведению

1) При запросе в JEI что делается из(нажатии U) Уголь (Грязная кучка пыли) (#4703/271) мир крашится. 

### Отчет о сбое

[crash-2022-12-28_15.35.28-client.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10314338/crash-2022-12-28_15.35.28-client.txt)
[latest.log](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10314340/latest.log)

**Comment by Xikaro** [comment]
is this an isolated case? Couldn't play

**Comment by Xikaro** [comment]
not repeated in 4.2.0
