### ISSUE TITLE
Breaking block crashing server 4.1.8 extended

### ISSUE THREAD

**Issue by BladeWolfK9000** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#64]
### Version modpack Used

Extended

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

Yes

### Steps to Reproduce

Server crash experienced when player breaks a block at the same time as their tool breaks or is on 1 HP. So far only seen on stone shovels, likely culprit is Inventory Bogo Sort as the player how constantly crashes the server has turned off "Enable Auto Hotbar Refill" and other players have broken tools and not caused a crash

### Crash Report

crash-2022-12-30_11.19.55-server.txt

**Comment by Xikaro** [comment]
![Screenshot_73](https://user-images.githubusercontent.com/55663835/210072240-3fe73832-b180-4647-a885-c4e71fb79495.png)
The bug is known and is currently being fixed by the developers.

**Comment by caxapexac** [comment]
Same problem, really annoying
Seems like its the conflict between the mod which automatically changes the broken item in your hand and the gregtech mod. But bot sure for real

**Comment by Xikaro** [comment]
update to version 4.1.10, and disable tool auto replacement in bogosort settings

**Comment by caxapexac** [comment]
Is it safe to update the existing 4 1.8 world?

**Comment by Xikaro** [comment]
fixed in 4.2.0
