### ISSUE TITLE
Updating 4.1.8 to 4.1.9

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#65]
### Your Question

Is it safe to just replacing the server saving the world? Are there any best practices updating the mod version?

I mean we are casually playing with some friends and I want to have the most recent mod version during our playthrough

**Comment by Xikaro** [comment]
the update takes place in a typical way, just change the folders, delete the old ones, and replace everything that is in the archive, leaving only the world

**Comment by caxapexac** [comment]
Потребовалось запустить мир в сингле и сохранить чтобы оно заработало на новой версии сервера, just fyi

**Comment by Xikaro** [comment]
Я на каждый релиз, обновляю наш сервак, проблем не было, мир под 40гб весит

**Comment by caxapexac** [comment]
Странно, у меня сервер запускался, но при заходе рвал коннект с клиентом через секунду
Сразу после пересохранение в сингле перестало
