### ISSUE TITLE
Bugged rendering

### ISSUE THREAD

**Issue by Blakil** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#67]
### Version modpack Used

Default

### Environment

Both

### New Worlds

Unsure

### Expected Behavior

При использовании шейдеров ожидается рендеринг объектов как следует.

### Actual Behavior

По факту же эти блоки не рендерятся, как и соседние к ним области, их "просвечивает", аналогичное происходит, если игра не поспевает рендерить чанки полностью.

Факт также в том, что я поставил для примера рядом два блока, что работают нормально и нет. Оба - одинакового типа, скриншот прикрепил.

Единственный режим, при котором эти блоки отображаются - Отключено, когда не работают даже встроенные, но при нём, что забавно возникают глюки у AE2 кабелей.

![weird1](https://user-images.githubusercontent.com/41113002/210913422-bd6a19a6-a268-424e-b0d2-3bcad71b2b27.png)
![weird2](https://user-images.githubusercontent.com/41113002/210913428-fc42e312-e085-4eed-8f1a-18697ec956f1.png)
![weird3](https://user-images.githubusercontent.com/41113002/210913431-8c79fec8-357f-43b1-8318-fba102ab6545.png)
![multiblock_casing](https://user-images.githubusercontent.com/41113002/210913434-91cb7651-52a4-4576-9c72-efac3149bd49.png)

### Steps to Reproduce

Просто поставить такие блоки, как топка, вентиляционный корпус, ламинированное стекло и т.д.

### Additional Information

Честно говоря, даже не знаю, чем могло быть вызвано, я даже немного покопался в файлах, но например блоки, взятые для демонстрации, виднеется, крайне схожи. Где и в чём они отличаются по объявлению и свойствам в файлах, вот главный вопрос, потому что отличие-то в любом случае есть, так как иначе блок бы корректно отображался, как я думаю. То же, по идее, решит проблему и со всеми другими блоками, имеющими такие проблемы с рендерингом.

**Comment by Blakil** [comment]
![image](https://user-images.githubusercontent.com/41113002/211174840-51023ae1-a351-49e9-8e00-c5c96dfbc346.png)
Небольшое дополнение - некоторые из таких блоков частично показываются в активном состоянии, может эта инфа поможет с определением проблемы.

**Comment by Xikaro** [comment]
В 4.2.0 не наблюдаю, если повторяется, открой снова
