### ISSUE TITLE
Gregification

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#68]
### Your Question

В 4.1.9 написано:

- Удален Gregification, есть ошибка инициализации с новой версией GT.

Не могу нагуглить этот мод вообще (кроме их гитхаба), у ребят поспрашивал - никто не знает, что это за мод, можно линк?)
И, если этот мод был контентно интересным, есть ли какие-то ориентировочные сроки когда он вернётся?

**Comment by SpeeeDCraft** [comment]
Разрабам являются разрабы Грега, мод добавляет совместимость других интересных модов с Грегом, существует только на Гите пока что, ориентировочной даты выхода мода нет.
