### ISSUE TITLE
Сервер крашится при попытке поспать (4.1.8)

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#69]
### Тип используемого модпака

Default

### Среда запуска

Дедик

### С какой стороны краш

Сервер

### Новые миры

Не уверен

### Действия по воспроизведению

Лёг в кровать - сервер лёг
Перезапустил, лёг опять - сервер лёг опять

### Отчет о сбое

[2023-01-09-1.log](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10369587/2023-01-09-1.log)

[crash-2023-01-09_00.51.46-server.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10369588/crash-2023-01-09_00.51.46-server.txt)

### Дополнительная информация

По логам судя по всему tfc печка, которая для выпекания стекла, она ночью пытается вычислить сколько угля потратилось и падает

**Comment by Xikaro** [comment]
Обновись до версии 4.1.11, там вроде это не наблюдалось, если не поможет, установи тут
https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/7d924cbc556fb153c7b31f64586f12b313ee32f5/serverfiles/server.properties#L3
так
max-tick-time=-1
