### ISSUE TITLE
Нерф сосуда, как хранилище.

### ISSUE THREAD

**Issue by Xikaro** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#7]
Попробовать сделать так, чтоб в сосуд можно было только пыли металла/куски руды кидать и категорию food 
<tfcflorae:food/*>
<tfcflorae:food/*>
 и ничего больше, это нужно, для исправления дюпа элементов позднего этапа, и чтоб не грузить скрипты массивами перечислений предметов с весом, которые увеличивают время загрузки сборки
Для хранения других вещей на раннем этапе есть ящик, из флорае(рецепт будет сделан), 
по вместимости он почти такой же, как если бы 4 сосуда стояло на земля, как примитивное хранилище.
![Screenshot_133](https://user-images.githubusercontent.com/55663835/190479978-aacf21cc-4c13-4813-bced-2b00c9ac22a8.png)

**Comment by SpeeeDCraft** [comment]
Будет сделано.
