### ISSUE TITLE
Упал сервер после того, как сломал кактус (4.1.8)

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#71]
### Version modpack Used

Default

### Environment

Дедик

### Side Crashed

Client and Server

### New Worlds

Yes

### Steps to Reproduce

Первый раз такое, до этого ломал и всё было норм. По логам что-то с падающими блоками (?)

Предположу, что из-за пинга после ломания нижнего блока кактуса я подошёл на место где находился кактус, и верхний его блок при падении пытался взаимодействовать с игроком, но не предполагалось, что кактусы будут падать на игроков

### Crash Report

[2023-01-09-3.log](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10376176/2023-01-09-3.log)
[crash-2023-01-09_21.45.22-server.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10376180/crash-2023-01-09_21.45.22-server.txt)

**Comment by Xikaro** [comment]
Это тоже самое, что я писал в #69, выполните предписания, что указано там, и ошибки не будет
