### ISSUE TITLE
Conflicting recipies in TFG-New-Horizons-4.1.11-server-extended

### ISSUE THREAD

**Issue by MechanID** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#72]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Unsure

### Expected Behavior

I want to craft steam macerator with only available recipie 
![recipie](https://user-images.githubusercontent.com/9780710/211416946-098f1c4e-8fd0-40ac-97dc-658694e3befe.png)

and expect to get steam macerator

### Actual Behavior

When all items placed on i see:
![on_workbench](https://user-images.githubusercontent.com/9780710/211417085-ea4f5845-2e1c-447e-b3a3-1a8e552812b1.png)
and this is steam miner.

### Steps to Reproduce

1 check recipie in NEI
2 put all items on crafting grid
3 check what result you have

### Additional Information

using "/ct recipes hand" with steam macerator in hand:
recipes.addShaped("gregtech:steam_macerator_bronze", <gregtech:machine:9>, [[<ore:gemDiamond>, <ore:pipeSmallFluidBronze>, <ore:gemDiamond>], [<ore:pipeSmallFluidBronze>, <gregtech:steam_casing>, <ore:pipeSmallFluidBronze>], [<ore:craftingPiston>, <ore:pipeSmallFluidBronze>, <ore:craftingPiston>]]);
recipes.addShaped("tfg/gregtech/steam_macerator", <gregtech:machine:9>, [[<gregtech:meta_gem_flawed:276> | <minecraft:diamond> | <gregtech:meta_gem_flawless:276>, <gregtech:fluid_pipe_normal:260>, <gregtech:meta_gem_flawed:276> | <minecraft:diamond> | <gregtech:meta_gem_flawless:276>], [<gregtech:fluid_pipe_normal:260>, <gregtech:steam_casing>, <gregtech:fluid_pipe_normal:260>], [<gregtech:meta_gear_small:260>, <gregtech:fluid_pipe_normal:260>, <gregtech:meta_gear_small:260>]]);

using "/ct recipes hand" with steam miner in hand:
recipes.addShaped("gregtech:steam_miner", <gregtech:machine:21>, [[<ore:gemDiamond>, <ore:pipeNormalFluidBronze>, <ore:gemDiamond>], [<ore:pipeNormalFluidBronze>, <gregtech:steam_casing>, <ore:pipeNormalFluidBronze>], [<ore:gearSmallBronze>, <ore:pipeNormalFluidBronze>, <ore:gearSmallBronze>]]);
recipes.addShaped("tfg/gregtech/steam_miner", <gregtech:machine:21>, [[<gregtech:meta_gem_flawed:276> | <minecraft:diamond> | <gregtech:meta_gem_flawless:276>, <gregtech:fluid_pipe_small:260>, <gregtech:meta_gem_flawed:276> | <minecraft:diamond> | <gregtech:meta_gem_flawless:276>], [<gregtech:fluid_pipe_small:260>, <gregtech:steam_casing>, <gregtech:fluid_pipe_small:260>], [<ore:craftingPiston>, <gregtech:fluid_pipe_small:260>, <ore:craftingPiston>]]);

**Comment by Xikaro** [comment]
not repeated in 4.2.0
