### ISSUE TITLE
Extended vanila furnace easy craft

### ISSUE THREAD

**Issue by Damodigy** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#73]
### Version modpack Used

Extended

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Ванильную печь нельзя скрафтить

### Actual Behavior

![image](https://user-images.githubusercontent.com/43088109/212311062-57e8b87f-fae5-4764-a1cd-9c7bb63802ba.png)

### Steps to Reproduce

Открыть рецепт печи от GT

**Comment by SpeeeDCraft** [comment]
Благодарим

**Comment by Xikaro** [comment]
fixed in 4.2.0
