### ISSUE TITLE
Медная пластина не перерабатывается в ГТ машинах

### ISSUE THREAD

**Issue by kirilsgekiss** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#77]
### Тип используемого модпака

Default

### Среда запуска

SP

### Новые миры

Да

### Ожидаемое поведение

Медная пластина дробится в медную пыль, как показывает JEI

### Фактическое поведение

Медная пластина не дробится в медную пыль, как показывает JEI

### Действия по воспроизведению

Положить медную пластину в паровой или электрический масератор

### Дополнительная информация

[screen-capture (2).webm](https://user-images.githubusercontent.com/49213594/212760659-77fd030b-7de0-4cf3-b594-848cd1684957.webm)

**Comment by kirilsgekiss** [comment]
Также не работает рецепт в форминг прессе (монета), в дуговой печке, экстракторе

**Comment by SpeeeDCraft** [comment]
Это баг в ГТ или баг в ТФК, мы так и не поняли, решается повторным добавлением идентичного рецепта. Хоть и крафттвикер/грувискрипт, должен начать ругаться, что что у нас дубликат рецепта, но нет, все будет нормально...
Постараемся исправить в 5.*
