### ISSUE TITLE
~7x выход олова из касситерита

### ISSUE THREAD

**Issue by kirilsgekiss** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#78]
### Ваш вопрос

Насколько оправдано получение 244 ед. жидкого олова из одной пыли касситерита? Я понимаю, что идея удвоенного выхода олова из касситерита по отношение к оловянной руде идёт из ГрегТеха, но в таком случае увеличенный выход жидкого олова применим только к не дробленной руде. Но ещё одно "удвоение" (х1.6) пылей, которые уже получили этот "греговский мультипликатор", выглядит странно.. 
Так же несколько забавно что Horse Power не имеет этого мультипликатора, но выход от лошадиной дробилки в целом несколько абсурден (но всё же этот случай выделяется).
Возможно это было бы оправданно, если жилы олова были крайне редки, но на личном опыте в СП соотношение найденных жил к другим рудам и так окей (+касситерит также встречается в жилах с халькопиритом).
![image](https://user-images.githubusercontent.com/49213594/213253562-a81f3f51-7f95-44e6-8090-04394b587ba3.png)
![image](https://user-images.githubusercontent.com/49213594/213257838-97276ec4-c75d-41b0-8c2f-4831c855cf24.png)

**Comment by SpeeeDCraft** [comment]
Из-за не редкости жил, **не** оправданно, ждем TFG R5.0.0
