### ISSUE TITLE
Система еды

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#91]
### Тип используемого модпака

Default

### Связанная проблема

В игре мало еды

### Ваше решение

Вернуть систему еды как в TFC 1.7.10 И сделать возможно использование еды из других модов

**Comment by Xikaro** [comment]
Планируется интеграция памса

**Comment by Xikaro** [comment]
Тут этому не место, будет реализовано в форке ТФК
