### ISSUE TITLE
Большой солнечный котёл

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#94]
### Тип используемого модпака

Default

### Связанная проблема

Надоело ставить много маленьких котёлков, организация "Котёльщики" требует новых, больший солнечных котлов!

### Ваше решение

Добавить большие солнечные котлы в альтернативу угольным

**Comment by GIBRID64r** [comment]
ЗА, хотя если так подумать то за созданием БСК обращаться к разрабам гт...

**Comment by Maximnety** [comment]
Разрабы хотели бы - добавили, а с Xikaro договориться можно

**Comment by Xikaro** [comment]
Вангую, они тебя пошлют в мягкой форме

**Comment by Xikaro** [comment]
Я не вижу смысла в БСК, от слова совсем

**Comment by GIBRID64r** [comment]
Мы видим, это по факту бесплатная энергия

**Comment by Maximnety** [comment]
Но ты то не пошлёшь в мягкой форме, поэтому я и обращаюсь здесь)

**Comment by Xikaro** [comment]
Не будет реализовано
