### ISSUE TITLE
Where is Nickel ore vein

### ISSUE THREAD

**Issue by MichMich003** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#96]
### Your Question

Hi i am playing TerraFirmaGreg New Horizons 4 1 11 since a month in a singelplayer game and i cant find nickel ore vein 
I have look in some other world with the vein finder witch can find ore vein in 6 chunk radius but after 2 hours in creative mode flying across the world i still cant find a single node...
i am the only one to have this issue ?
thank for reading =)

**Comment by MichMich003** [comment]
Nickel ore are spawning normaly in other dimension (deimos)

**Comment by kirilsgekiss** [comment]
Hi @MichMich003, I personally obtain nickel from Soapstone ore veins. It contains Pentlandite ore that can be smelted into the nickel. The same is for Trona ore veins, but those are more rare. As you can see from [Ore Generation table](https://docs.google.com/spreadsheets/d/1JG5J7Pam633_ZGha9nNXSfAI33Thv3tf/edit#gid=1125154267), Earth Nickel spawns only in 2 types of rocks, so no surprise you could find it even after 2 hours.
Also you can get Nickel as a side product from different Iron, Platinum ores, as well as from Gold ore if you already have GregTech ore processing. (check recipe for Tiny Nickel dust in JEI) 
Hope it helps!
