### ISSUE TITLE
Crash upon viewing AE interface that is sorting by InventoryTweaks

### ISSUE THREAD

**Issue by BurgerFan45** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#97]
### Version modpack Used

Default

### Environment

Server Multiplayer & Singleplayer

### Side Crashed

Client

### New Worlds

Unsure

### Steps to Reproduce

1 Have an AE system with an interface
2 Click the sort button in the interface until it lands on Inventory Tweaks
3 Crash

### Crash Report

Tested in singleplayer, but first occurred in multiplayer.
Scrolling through the sort method of an ME interface will cause the client to crash when it lands the 'Inventory Tweaks' sort method.
In multiplayer I could reconnect but when I tried to replicate it in singleplayer I had to force close Minecraft.
Only workaround I've found is to Remove and replace the interface to reset the sort method.
[crash-2023-02-16_04.51.04-client.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10746555/crash-2023-02-16_04.51.04-client.txt)
[crash-2023-02-16_04.51.06-client.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/10746556/crash-2023-02-16_04.51.06-client.txt)
![sort method](https://user-images.githubusercontent.com/24676340/219129773-49777f3c-b61c-4351-9b99-f41995af7ca5.png)

**Comment by Xikaro** [comment]
fixed in 4.2.0
