### ISSUE TITLE
java.lang.NoClassDefFoundError: gregtech/api/items/toolitem/IGTTool

### ISSUE THREAD

**Issue by UrbanSide** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#98]
### Тип используемого модпака

Default

### Среда запуска

Forge Server

### С какой стороны краш

Сервер

### Новые миры

Да

### Действия по воспроизведению

Без понятия,я просто копал лопатой,товарищ стоял рядом смотрел рецепты крафта.

### Отчет о сбое

https://mclo.gs/WeuCjT3

**Comment by UrbanSide** [comment]
А так же вопрос "Превратил энергию в кинетическую" такое выдает на ровном месте убивая перса.

**Comment by Xikaro** [comment]
Это с обновой гт на 2.5+ должно исправится, так как инструменты поломаны были, после обновы модпака на 4.2, все инструменты гт исчезнут, так как они были переработаны

**Comment by UrbanSide** [comment]
> Это с обновой гт на 2.5+ должно исправится, так как инструменты поломаны были, после обновы модпака на 4.2, все инструменты гт исчезнут, так как они были переработаны

Понял,принял,спасибо.Осталось понять причины рандомных смертей)
