### ISSUE TITLE
Crash when using a shutter module on liquide pipe with liquide in it

### ISSUE THREAD

**Issue by MichMich003** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#99]
### Version modpack Used

Default

### Environment

singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

get water in a pipe (bronze or wood pipe) with a primitive pump
right click  with a shutter module on your pipe (the shutter  module need to be inside the connection between pipe) (to block liquide)
crash.

### Crash Report

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// This doesn't make any sense!

Time: 2023-01-10 20:50:13 CET
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: field_184828_bq
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: field_184828_bq
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:321)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 747351040 bytes (712 MB) / 5454168064 bytes (5201 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 69
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 182 mods loaded, 182 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                             | Source                                                      | Signature                                |
       |:------ |:------------------------ |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                              | minecraft.jar                                               | None                                     |
       | LCHIJA | mcp                      | 9.42                                | minecraft.jar                                               | None                                     |
       | LCHIJA | bansoukou                | 4.3.1                               | minecraft.jar                                               | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                           | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy        | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCHIJA | micdoodlecore            | 4.0.4                               | minecraft.jar                                               | None                                     |
       | LCHIJA | itemphysic               | 1.4.0                               | minecraft.jar                                               | None                                     |
       | LCHIJA | littletilescore          | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCHIJA | smoothfontcore           | mc1.12.2-2.1.4                      | minecraft.jar                                               | None                                     |
       | LCHIJA | mixinbooter              | 7.0                                 | minecraft.jar                                               | None                                     |
       | LCHIJA | darkness                 | 0.5.0                               | darkness-forge-1.12.x-0.5.0.jar                             | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                               | minecraft.jar                                               | None                                     |
       | LCHIJA | opencomputers|core       | 1.8.0-snapshot-20220917             | minecraft.jar                                               | None                                     |
       | LCHIJA | randompatches            | 1.12.2-1.22.1.10                    | randompatches-1.12.2-1.22.1.10.jar                          | None                                     |
       | LCHIJA | smoothfont               | mc1.12.2-2.1.4                      | SmoothFont-mc1.12.2-2.1.4.jar                               | None                                     |
       | LCHIJA | ctm                      | MC1.12.2-1.0.2.31                   | CTM-MC1.12.2-1.0.2.31.jar                                   | None                                     |
       | LCHIJA | appliedenergistics2      | rv6-stable-7-extended_life-v0.54.17 | appliedenergistics2-rv6-stable-7-extended_life-v0.54.17.jar | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux             | 2.1.1                               | RedstoneFlux-1.12-2.1.1.1-universal.jar                     | None                                     |
       | LCHIJA | brandonscore             | 2.4.20                              | BrandonsCore-1.12.2-2.4.20.162-universal.jar                | None                                     |
       | LCHIJA | aenetvistool             | 1.0.3                               | AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar                | None                                     |
       | LCHIJA | baubles                  | 1.12.2-1.6.0                        | Baubles-1.12.2-1.0.6.0.jar                                  | None                                     |
       | LCHIJA | p455w0rdslib             | 2.3.161                             | p455w0rdslib-1.12.2-2.3.161.jar                             | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | ae2wtlib                 | 1.0.35                              | AE2WTLib-1.12.2-1.0.35.jar                                  | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
       | LCHIJA | aeadditions              | 1.3.8                               | AEAdditions-1.12.2-1.3.8.jar                                | None                                     |
       | LCHIJA | creativecore             | 1.10.0                              | CreativeCore_v1.10.70_mc1.12.2.jar                          | None                                     |
       | LCHIJA | ambientsounds            | 3.0                                 | AmbientSounds_v3.1.7_mc1.12.2.jar                           | None                                     |
       | LCHIJA | architecturecraft        | @VERSION@                           | architecturecraft-1.12-3.98.jar                             | None                                     |
       | LCHIJA | galacticraftcore         | 4.0.4                               | Galacticraft-1.12.2-4.0.4.jar                               | None                                     |
       | LCHIJA | galacticraftplanets      | 4.0.4                               | Galacticraft-1.12.2-4.0.4.jar                               | None                                     |
       | LCHIJA | crafttweaker             | 4.1.20                              | CraftTweaker2-1.12-4.1.20.682.jar                           | None                                     |
       | LCHIJA | mjrlegendslib            | 1.12.2-1.2.1                        | MJRLegendsLib-1.12.2-1.2.1.jar                              | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extraplanets             | 1.12.2-0.7.4                        | ExtraPlanets-1.12.2-0.7.4.jar                               | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | planetprogression        | 1.12.2-0.4.8                        | PlanetProgression-1.12.2-0.4.8.jar                          | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | asmodeuscore             | 0.0.30                              | AsmodeusCore-1.12.2-0.0.31.jar                              | None                                     |
       | LCHIJA | astikorcarts             | tfc-1.12.2-0.1.2.9                  | astikorcarts-tfc-1.12.2-0.1.2.9.jar                         | None                                     |
       | LCHIJA | charset                  | 0.5.6.6                             | Charset-Lib-0.5.6.6.jar                                     | None                                     |
       | LCHIJA | mtlib                    | 3.0.7                               | MTLib-3.0.7.jar                                             | None                                     |
       | LCHIJA | modtweaker               | 4.0.19                              | modtweaker-4.0.20.11.jar                                    | None                                     |
       | LCHIJA | jei                      | 4.24.2                              | HadEnoughItems_1.12.2-4.24.2.jar                            | None                                     |
       | LCHIJA | athenaeum                | 1.12.2-1.19.5                       | athenaeum-1.12.2-1.19.5.jar                                 | None                                     |
       | LCHIJA | betterchat               | 1.4                                 | betterchat-1.4.jar                                          | None                                     |
       | LCHIJA | betterfoliage            | 2.3.2                               | BetterFoliage-MC1.12-2.3.3.jar                              | None                                     |
       | LCHIJA | betterp2p                | 1.12.2-1.2.3-extended_life          | betterp2p-1.12.2-1.2.3-extended_life.jar                    | None                                     |
       | LCHIJA | blur                     | 1.0.4-14                            | Blur-1.0.4-14.jar                                           | None                                     |
       | LCHIJA | modularui                | 1.0.6                               | modularui-1.0.6.jar                                         | None                                     |
       | LCHIJA | bogosorter               | 1.2.1                               | bogosorter-1.2.1.jar                                        | None                                     |
       | LCHIJA | bookshelf                | 2.3.590                             | Bookshelf-1.12.2-2.3.590.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildinggadgets          | 2.8.4                               | BuildingGadgets-2.8.4.jar                                   | None                                     |
       | LCHIJA | carryon                  | 1.12.3                              | carryon-1.12.2-1.12.6.20.jar                                | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCHIJA | catwalks                 | 1.12.2-4.0.45                       | catwalks-1.12.2-4.0.45.jar                                  | None                                     |
       | LCHIJA | tfc                      | 1.7.23.181                          | TerraFirmaCraft-MC1.12.2-1.7.23.181-patched.jar             | None                                     |
       | LCHIJA | cellars                  | 1.24.3                              | CellarAddon-1.24.3.jar                                      | None                                     |
       | LCHIJA | loliasm                  | 5.6                                 | censoredasm5.6.jar                                          | None                                     |
       | LCHIJA | chisel                   | MC1.12.2-1.0.2.45                   | Chisel-MC1.12.2-1.0.2.45.jar                                | None                                     |
       | LCHIJA | chunkanimator            | 1.12.2-1.2                          | ChunkAnimator-1.12.2-1.2.1.jar                              | None                                     |
       | LCHIJA | clumps                   | 3.1.2                               | Clumps-3.1.2.jar                                            | None                                     |
       | LCHIJA | extendedrenderer         | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCHIJA | coroutil                 | 1.12.1-1.2.37                       | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCHIJA | configmod                | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCHIJA | corpse                   | 1.12.2-1.0.8                        | corpse-1.12.2-1.0.8.jar                                     | None                                     |
       | LCHIJA | craftingtweaks           | 9.0.1                               | CraftingTweaks_1.12.2-9.0.1.jar                             | None                                     |
       | LCHIJA | craftpresence            | 2.0.0-alpha.2                       | CraftPresence-2.0.0-alpha.2+1.12.2-universal.jar            | None                                     |
       | LCHIJA | ctgui                    | 1.0.0                               | CraftTweaker2-1.12-4.1.20.682.jar                           | None                                     |
       | LCHIJA | crafttweakerjei          | 2.0.3                               | CraftTweaker2-1.12-4.1.20.682.jar                           | None                                     |
       | LCHIJA | customloadingscreen      | 1.12.2-1.5.7                        | CustomLoadingScreen-1.12.2-1.5.7.jar                        | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.1                        | journeymap-1.12.2-5.7.1.jar                                 | None                                     |
       | LCHIJA | defaultoptions           | 9.2.8                               | DefaultOptions_1.12.2-9.2.8.jar                             | None                                     |
       | LCHIJA | gregtech                 | 2.4.5-beta                          | gregtech-1.12.2-2.4.5-beta.jar                              | None                                     |
       | LCHIJA | devtech                  | 2.1.2                               | devtech-2.1.2.jar                                           | None                                     |
       | LCHIJA | dropt                    | 1.12.2-1.19.3                       | dropt-1.12.2-1.19.3.jar                                     | None                                     |
       | LCHIJA | orelib                   | 3.6.0.1                             | OreLib-1.12.2-3.6.0.1.jar                                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                | @VERSION@                           | DynamicSurroundings-1.12.2-3.6.3.jar                        | None                                     |
       | LCHIJA | enderstorage             | 2.4.7.null                          | EnderStorage-1.12.2-2.4.7.jar                               | None                                     |
       | LCHIJA | renderlib                | 1.1.10                              | RenderLib-1.12.2-1.1.10.jar                                 | None                                     |
       | LCHIJA | entityculling            | 6.2.5                               | EntityCulling-1.12.2-6.2.5.jar                              | None                                     |
       | LCHIJA | extracpus                | 1.12.2-1.2.1                        | extracpus-1.12.2-1.2.1.jar                                  | None                                     |
       | LCHIJA | findme                   | 1.0.0                               | findme-1.12.2-1.0.0.jar                                     | None                                     |
       | LCHIJA | konkrete                 | 1.6.0                               | konkrete_forge_1.6.0_MC_1.12-1.12.2.jar                     | None                                     |
       | LCHIJA | fancymenu                | 2.13.2                              | fancymenu_forge_2.13.2_MC_1.12-1.12.2.jar                   | None                                     |
       | LCHIJA | fantasticlib             | 1.12.2.047                          | FantasticLib-1.12.2.047.jar                                 | None                                     |
       | LCHIJA | fasterladderclimbing     | 0.1-146                             | FasterLadderClimbing-1.12-0.1-146.jar                       | None                                     |
       | LCHIJA | fastbench                | 1.7.4                               | FastWorkbench-1.12.2-1.7.4.jar                              | None                                     |
       | LCHIJA | firmalife                | 0.5.1                               | firmalife-0.5.1.jar                                         | None                                     |
       | LCHIJA | tfcflorae                | 1.4.6                               | TFC-Florae-MC1.12.2-1.4.6.jar                               | None                                     |
       | LCHIJA | floraefixes              | 1.0                                 | floraefixes-1.0.jar                                         | None                                     |
       | LCHIJA | ae2fc                    | 2.4.10-r                            | Fluid Craft for AE2-2.4.10-r.jar                            | None                                     |
       | LCHIJA | foamfix                  | @VERSION@                           | foamfix-0.10.15-1.12.2.jar                                  | None                                     |
       | LCHIJA | forgemultipartcbe        | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe            | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | LCHIJA | minecraftmultipartcbe    | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | LCHIJA | fpsreducer               | mc1.12.2-1.20                       | FpsReducer-mc1.12.2-1.20.jar                                | None                                     |
       | LCHIJA | ftbbackups               | 1.1.0.1                             | FTBBackups-1.1.0.1.jar                                      | None                                     |
       | LCHIJA | ftblib                   | 5.4.7.2                             | FTBLib-5.4.7.2.jar                                          | None                                     |
       | LCHIJA | ftbutilities             | 5.4.1.131                           | FTBUtilities-5.4.1.131.jar                                  | None                                     |
       | LCHIJA | itemfilters              | 1.0.4.2                             | ItemFilters-1.0.4.2.jar                                     | None                                     |
       | LCHIJA | ftbquests                | 1202.9.0.15                         | FTBQuests-1202.9.0.15.jar                                   | None                                     |
       | LCHIJA | opencomputers            | 1.8.0-snapshot-20220917             | OpenComputers-MC1.12.2-1.8.0-snapshot-20220917+efb20a2.jar  | None                                     |
       | LCHIJA | galacticcomputers        | 1.0.0                               | GalacticComputers-1.0.0.jar                                 | None                                     |
       | LCHIJA | grandeconomy             | 2.1.2                               | GrandEconomy-1.12.2-2.1.2.jar                               | None                                     |
       | LCHIJA | gcym                     | 1.1.5                               | GregicalityMultiblocks-1.12.2-1.1.5.jar                     | None                                     |
       | LCHIJA | gregtechfoodoption       | 1.12.2-1.8.1                        | GregTech Food Option-1.12.2-1.8.2.jar                       | None                                     |
       | LCHIJA | groovyscript             | 0.0.2                               | groovyscript-0.0.2.jar                                      | None                                     |
       | LCHIJA | hgp                      | Release                             | hgp-1.0.jar                                                 | None                                     |
       | LCHIJA | theoneprobe              | 1.4.28                              | theoneprobe-1.12-1.4.28.jar                                 | None                                     |
       | LCHIJA | horsepower               | 2.6.7-TFC                           | HorsePowerTFC-MC1.12.2-2.6.7.jar                            | None                                     |
       | LCHIJA | tfgmod                   | 2.0.6                               | tfgmod-2.0.6.jar                                            | None                                     |
       | LCHIJA | hotornot                 | 1.5                                 | hotornot-1.5.jar                                            | None                                     |
       | LCHIJA | htmltech                 | 0.2.2-beta                          | htmlTech-1.12.2-0.2.2-beta.jar                              | None                                     |
       | LCHIJA | inventoryhud             | 3.4.4                               | InventoryHUD-1.12.2.forge-3.4.4.jar                         | None                                     |
       | LCHIJA | inworldcrafting          | 1.12.2-1.2.0                        | inworldcrafting-1.12.2-1.2.0-universal.jar                  | None                                     |
       | LCHIJA | jeiutilities             | 0.2.10                              | JEI-Utilities-1.12.2-0.2.10.jar                             | None                                     |
       | LCHIJA | jetif                    | 1.5.2                               | jetif-1.12.2-1.5.2.jar                                      | None                                     |
       | LCHIJA | jsg                      | 1.12.2-4.10.1.1                     | jsg-1.12.2-4.10.1.1-client.jar                              | None                                     |
       | LCHIJA | jecalculation            | 1.12.2-3.2.7                        | JustEnoughCalculation-1.12.2-3.2.7.jar                      | None                                     |
       | LCHIJA | keywizard                | 1.12.2-1.7.3                        | keywizard-1.12.2-1.7.3.jar                                  | None                                     |
       | LCHIJA | legendarytooltips        | 1.1.8                               | LegendaryTooltips-1.12.2-1.1.8.jar                          | None                                     |
       | LCHIJA | littletiles              | 1.5.0                               | LittleTiles_v1.5.65_mc1.12.2.jar                            | None                                     |
       | LCHIJA | loottweaker              | 0.3.1                               | LootTweaker-0.3.1+MC1.12.2.jar                              | None                                     |
       | LCHIJA | mechtech                 | 1.1.0-beta                          | mechtech-1.1.0-beta.jar                                     | None                                     |
       | LCHIJA | moreoverlays             | 1.15.1                              | moreoverlays-1.15.1-mc1.12.2.jar                            | None                                     |
       | LCHIJA | mousetweaks              | 3.1.2                               | MouseTweaks-3.1.2-mc1.12.2.jar                              | None                                     |
       | LCHIJA | supermartijn642configlib | 1.1.6                               | supermartijn642configlib-1.1.6-forge-mc1.12.jar             | None                                     |
       | LCHIJA | supermartijn642corelib   | 1.1.0                               | supermartijn642corelib-1.1.0-forge-mc1.12.jar               | None                                     |
       | LCHIJA | movingelevators          | 1.3.10                              | movingelevators-1.3.10-forge-mc1.12.jar                     | None                                     |
       | LCHIJA | mrtjpcore                | 2.1.4.43                            | MrTJPCore-1.12.2-2.1.4.43-universal.jar                     | None                                     |
       | LCHIJA | multiblocktweaker        | 1.12.2-stable-gtceu-1.8.2           | multiblocktweaker-1.12.2-stable-gtceu-1.8.2.jar             | None                                     |
       | LCHIJA | noadvancements           | 1.12.2.002                          | NoAdvancements-1.12.2.002.jar                               | None                                     |
       | LCHIJA | oxygen_core              | 0.11.4                              | oxygen-core-1.12.2-0.11.4.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_cp_ge             | 0.11.1                              | oxygen-cp-grand-economy-1.12.2-0.11.2.jar                   | e48bc44997dd6e7539e0c065b588c11fbdd1f650 |
       | LCHIJA | oxygen_exchange          | 0.11.1                              | oxygen-exchange-1.12.2-0.11.1.jar                           | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_mail              | 0.11.2                              | oxygen-mail-1.12.2-0.11.2.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_market            | 0.11.2                              | oxygen-market-1.12.2-0.11.2.jar                             | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_menu              | 0.11.1                              | oxygen-menu-1.12.2-0.11.1.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_pinteraction      | 0.11.1                              | oxygen-player-interaction-1.12.2-0.11.1.jar                 | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_playerslist       | 0.11.1                              | oxygen-players-list-1.12.2-0.11.1.jar                       | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_shop              | 0.11.1                              | oxygen-shop-1.12.2-0.11.1.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | oxygen_teleportation     | 0.11.1                              | oxygen-teleportation-1.12.2-0.11.1.jar                      | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCHIJA | particleculling          | v1.3                                | particleculling-1.12.2-v1.3.1.jar                           | None                                     |
       | LCHIJA | performant               | 1.12.2-1.5                          | performant-1.11.jar                                         | None                                     |
       | LCHIJA | placebo                  | 1.6.0                               | Placebo-1.12.2-1.6.0.jar                                    | None                                     |
       | LCHIJA | projectred-core          | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-Base.jar                        | None                                     |
       | LCHIJA | projectred-integration   | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
       | LCHIJA | projectred-transmission  | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
       | LCHIJA | projectred-fabrication   | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-fabrication.jar                 | None                                     |
       | LCHIJA | projectred-illumination  | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-lighting.jar                    | None                                     |
       | LCHIJA | puddles                  | 1.1                                 | Puddles-1.1.jar                                             | None                                     |
       | LCHIJA | resourceloader           | 1.5.3                               | ResourceLoader-MC1.12.1-1.5.3.jar                           | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | jeid                     | 2.0.2-SNAPSHOT                      | RoughlyEnoughIDs-1.12.2-2.0.2-CubicCompat.jar               | None                                     |
       | LCHIJA | simplelogin              | 1.2.4-beta+build127                 | simplelogin-1.2.4-beta+build127.jar                         | None                                     |
       | LCHIJA | sinkorswim               | 1.0.0                               | Sink-1.0.0.jar                                              | None                                     |
       | LCHIJA | sledgehammer             | 1.12.2-2.0.21                       | Sledgehammer-1.12.2-2.0.21.jar                              | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
       | LCHIJA | soundfilters             | 0.12.1_for_1.12                     | SoundFilters-0.12.1_for_1.12.jar                            | None                                     |
       | LCHIJA | spatialservermod         | 1.3.1                               | spatialservermod-1.3.1.jar                                  | None                                     |
       | LCHIJA | sasit                    | 1.1.32                              | StuffASockInIt-1.12.2-1.1.32.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tfcthings                | 1.3.5                               | terrafirmathings-1.3.5.jar                                  | None                                     |
       | LCHIJA | aged_drinks              | 1.0.1                               | TFCAgedDrinks-1.0.7.jar                                     | None                                     |
       | LCHIJA | tfcalloycalc             | 1.0                                 | TFCAlloyCalc-1.0.jar                                        | None                                     |
       | LCHIJA | tfcambiental             | 2.1                                 | tfcambiental-2.3.jar                                        | None                                     |
       | LCHIJA | tfcfarming               | 1.1.4                               | tfcfarming-1.1.4.jar                                        | None                                     |
       | LCHIJA | tfcmedicinal             | 1.0.0                               | TFCMedicinal-1.0.6.jar                                      | None                                     |
       | LCHIJA | tfctech                  | 1.2.16                              | TFCTech-Unofficial-MC1.12.2-1.2.16.jar                      | None                                     |
       | LCHIJA | tfctowerheat             | 1.2                                 | tfctowerheat-1.2.jar                                        | None                                     |
       | LCHIJA | thah                     | 1.1.1                               | thah-1.1.1.jar                                              | None                                     |
       | LCHIJA | tips                     | 1.0.9                               | Tips-1.12.2-1.0.9.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | toastcontrol             | 1.8.1                               | Toast Control-1.12.2-1.8.1.jar                              | None                                     |
       | LCHIJA | toolbelt                 | 1.9.14                              | ToolBelt-1.12.2-1.9.14.jar                                  | None                                     |
       | LCHIJA | topaddons                | 1.12.2-1.13.0                       | topaddons-1.12.2-1.13.0.jar                                 | None                                     |
       | LCHIJA | topextras                | 1.0.1                               | topextras-1.12.2-1.0.1.jar                                  | None                                     |
       | LCHIJA | travelersbackpack        | 1.0.35                              | TravelersBackpack-1.12.2-1.0.35.jar                         | None                                     |
       | LCHIJA | treechop                 | 0.14.6                              | TreeChop-1.12.2-0.14.7.jar                                  | None                                     |
       | LCHIJA | universaltweaks          | 1.12.2-1.2.0                        | UniversalTweaks-1.12.2-1.2.0.jar                            | None                                     |
       | LCHIJA | waterflasks              | 1.9                                 | waterflasks-1.9.jar                                         | None                                     |
       | LCHIJA | weather2                 | 2.7.7-alpha                         | Weather2Remastered-1.12.2-2.7.7-alpha.jar                   | None                                     |
       | LCHIJA | wct                      | 3.12.97                             | WirelessCraftingTerminal-1.12.2-3.12.97.jar                 | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | wft                      | 1.0.4                               | WirelessFluidTerminal-1.12.2-1.0.4.jar                      | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | wit                      | 1.0.2                               | WirelessInterfaceTerminal-1.12.2-1.0.2.jar                  | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | wpt                      | 1.0.3                               | WirelessPatternTerminal-1.12.2-1.0.3.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | xtones                   | 1.2.2                               | Xtones-1.2.2.jar                                            | None                                     |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.9.2                      | phosphor-1.12.2-0.2.9.2-SNAPSHOT-universal.jar              | None                                     |
  Loaded coremods (and transformers): GTFOMixinPlugin (GregTech Food Option-1.12.2-1.8.2.jar)
                                        
                                      -Bansoukou- (_bansoukou-4.3.1.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-1.12.2-1.2.1.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-1.12.2-2.0.2-CubicCompat.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      JeiUtilitiesLoadingPlugin (JEI-Utilities-1.12.2-0.2.10.jar)
                                        com.github.vfyjxf.jeiutilities.asm.JeiUtilitiesClassTransformer
                                      PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.2-SNAPSHOT-universal.jar)
                                        
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.4.5-beta.jar)
                                        gregtech.core.GregTechTransformer
                                      SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.0-forge-mc1.12.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      RenderLibPlugin (RenderLib-1.12.2-1.1.10.jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.2.0.jar)
                                        
                                      KonkreteCore (konkrete_forge_1.6.0_MC_1.12-1.12.2.jar)
                                        
                                      MixinBooter (!mixinbooter-7.0.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.2.5.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      BogoSorter-Core (bogosorter-1.2.1.jar)
                                        
                                      ModularUI-Core (modularui-1.0.6.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Players List Core Plugin (oxygen-players-list-1.12.2-0.11.1.jar)
                                        austeretony.oxygen_playerslist.common.core.PlayersListClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      GroovyScript-Core (groovyscript-0.0.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      LoliASM (censoredasm5.6.jar)
                                        
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      FluidCraftCore (Fluid Craft for AE2-2.4.10-r.jar)
                                        com.glodblock.github.coremod.FCClassTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.65_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      FMCore (fancymenu_forge_2.13.2_MC_1.12-1.12.2.jar)
                                        
                                      darkness (darkness-forge-1.12.x-0.5.0.jar)
                                        io.github.yamporg.darkness.asm.WorldProviderTransformer
                                        io.github.yamporg.darkness.asm.EntityRendererTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.8.0-snapshot-20220917+efb20a2.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  AE2 Version: stable rv6-stable-7-extended_life-v0.54.17 for Forge 14.23.5.2847
  AE2 Integration: IC2:OFF, GTCE:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown

**Comment by Xikaro** [comment]
fixed in 4.2.0
